test

diff --git a/resources/bin/start-laravel b/resources/bin/start-laravel
--- a/resources/bin/start-laravel
+++ b/resources/bin/start-laravel
@@ -47,26 +47,26 @@ chown -R www-data:www-data /home/composer
 
 
 
-echo "Running composer"
-su -c "composer install --optimize-autoloader --prefer-dist" -s /bin/sh www-data
-if [ ! -f /src/composer.lock ]; then
-    echo "Could not find /src/composer.lock. Did you map Laravel root folder (containing composer.json) to docker container /src folder? Example: docker run .. -v /var/www/html/laravelproject:/src"
-    exit 1
-fi
+#echo "Running composer"
+#su -c "composer install --optimize-autoloader --prefer-dist" -s /bin/sh www-data
+#if [ ! -f /src/composer.lock ]; then
+#    echo "Could not find /src/composer.lock. Did you map Laravel root folder (containing composer.json) to docker container /src folder? Example: docker run .. -v /var/www/html/laravelproject:/src"
+#    exit 1
+#fi
 
 
 
-echo "Making docker-laravel bin files executable."
-chmod +x /usr/local/bin/setup-laravel-cron
-chmod +x /usr/local/bin/create-laravel-env-file.php
-chmod +x /src/artisan
+#echo "Making docker-laravel bin files executable."
+#chmod +x /usr/local/bin/setup-laravel-cron
+#chmod +x /usr/local/bin/create-laravel-env-file.php
+#chmod +x /src/artisan
 
 
 
 
 # Cron jobs.
-echo "Setting up cron jobs for laravel."
-su -c "/usr/local/bin/setup-laravel-cron" -s /bin/sh www-data
+#echo "Setting up cron jobs for laravel."
+#su -c "/usr/local/bin/setup-laravel-cron" -s /bin/sh www-data
 
 
 
@@ -78,11 +78,11 @@ su -c '/usr/local/bin/create-laravel-env-file.php' -s /bin/sh www-data
 
 
 # Migrate database.
-su -c "/src/artisan down" -s /bin/sh www-data
-su -c "/src/artisan storage:link" -s /bin/sh www-data
-su -c "/src/artisan migrate --force" -s /bin/sh www-data
-su -c "/src/artisan optimize" -s /bin/sh www-data
-su -c "/src/artisan up" -s /bin/sh www-data
+#su -c "/src/artisan down" -s /bin/sh www-data
+#su -c "/src/artisan storage:link" -s /bin/sh www-data
+#su -c "/src/artisan migrate --force" -s /bin/sh www-data
+#su -c "/src/artisan optimize" -s /bin/sh www-data
+#su -c "/src/artisan up" -s /bin/sh www-data
 
 
 
@@ -96,20 +96,20 @@ chmod -R 0777 /src
 rm /tmp/laravel-start-in-progress
 
 # Only start php-fpm if successful ...
-if [ -f /src/composer.lock ]; then
-   echo "Starting the cron service"
-   /usr/sbin/cron
+#if [ -f /src/composer.lock ]; then
+#   echo "Starting the cron service"
+#   /usr/sbin/cron
+#
+#   echo "Starting supervisord and laravel worker"
+#   service supervisor restart
+#   /usr/bin/supervisorctl reread
+#   /usr/bin/supervisorctl update
+#   /usr/bin/supervisorctl start laravel-worker:*
 
-   echo "Starting supervisord and laravel worker"
-   service supervisor restart
-   /usr/bin/supervisorctl reread
-   /usr/bin/supervisorctl update
-   /usr/bin/supervisorctl start laravel-worker:*
 
+#   echo "Starting php-fpm"
+#   /usr/local/sbin/php-fpm
 
-   echo "Starting php-fpm"
-   /usr/local/sbin/php-fpm
-
-else
-    echo "ERROR: could not find /src/composer.lock in laravel php container.... Did you mount laravel root dir as a volume to /src? You should..."
-fi
+#else
+#    echo "ERROR: could not find /src/composer.lock in laravel php container.... Did you mount laravel root dir as a volume to /src? You should..."
+#fi
